### ISSUE TITLE
Auto-off time not working with long off times

### ISSUE THREAD

**Issue by spaceg00se-r** [Plankske/hb-virtual-switch#3]
**Describe Your Problem:**
Hi. I have a virtual Switch configured in this plugin (not stateful) and I want it to power off after 3 hours. So I set the auto-off time to 10800000 ms. However, it seems that this is not working. Is there a maximum amount of time that is supported or might this be a bug? 

I'm running the latest official versions of Homebridge and this plugin.

**Comment by Plankske** [comment]
> **Describe Your Problem:**
> 
> Hi. I have a virtual Switch configured in this plugin (not stateful) and I want it to power off after 3 hours. So I set the auto-off time to 10800000 ms. However, it seems that this is not working. Is there a maximum amount of time that is supported or might this be a bug? 
> 
> 
> 
> I'm running the latest official versions of Homebridge and this plugin.

This should not be a problem ( max timer is about 25 days). Will check it out and add some debug code to keep track of long timer countdowns in the next couple of weeks.

**Comment by spaceg00se-r** [comment]
Hm... I have a thought on the issue. In my homekit system I have a few Shellies. Due do the fact the the Shelly plugin somhow looses connection to some of the older devices I had to set up a cronjob that restarts Homebridge every 6 hours. Could this be the problem? Does the timer stop when the system restarts? If so, could this be solved by bringing the switches that have a timer to the timer state they were in after a reboot?

**Comment by Plankske** [comment]
Thanks for the additional information. Let me look into this. Give me some time to get back to you.

On Oct 5, 2024, at 2:32 PM, spaceg00se-r ***@***.***> wrote:

﻿

Hm... I have a thought on the issue. In my homekit system I have a few Shellies. Due do the fact the the Shelly plugin somhow looses connection to some of the older devices I had to set up a cronjob that restarts Homebridge every 6 hours. Could this be the problem? Does the timer stop when the system restarts? If so, could this be solved by bringing the switches that have a timer to the timer state they were in after a reboot?

**Comment by spaceg00se-r** [comment]
Hi @Plankske. Did you already have a chance to have a look at it? Cheers, Chris

**Comment by Plankske** [comment]
@spaceg00se-r : i have been running multiple tests with times upto 4 hours and connect replicate your problem. Once switched one, the switch turns off after the set time. 
Currently, restarting in its last state for non-stateful switches is not supported as I have no way to know how much time was left on the timer when Homebridge shut down. 
That said, I am open to suggestions provided the solution is lightweight and within the 'HomeBridge Verified' guidelines.

**Comment by spaceg00se-r** [comment]
I looked into your code and wouldn't it be enough to persist the _timerEndTime_ on shutdown and probably some variable specifying that the timer was still running and then restore the switch with the persisted end time on bootup?

**Comment by MorelloCherry** [comment]
Perhaps storing the expected switch-off time in UTC? This would allow at least some sort of recoverability in case homebridge was restarted

**Comment by spaceg00se-r** [comment]
That sounds like a good idea.

**Comment by spaceg00se-r** [comment]
@Plankske What do you think about the suggestion?

**Comment by Plankske** [comment]
I like it and I will look into it. Think it will work. I just need a little more time before I can get to it ...

**Comment by spaceg00se-r** [comment]
@Plankske great to hear. Thanks! Let me know if you need any assistance.

**Comment by Plankske** [comment]
Just pushed version 1.2.0 which includes persistent timers. I.e. persistent through Homebridge restarts.
Let me know if this works for you.

**Comment by spaceg00se-r** [comment]
Hey @Plankske. Nice to hear that you pushed the update. I'll install it right away and test the new feature :-)! Thanks a lot!

**Comment by spaceg00se-r** [comment]
Hi @Plankske. I tested the new release and for me it seems that the switch will end up in turned off state if it is turned on and then homebridge is restarted. You can find my configuration in the attached screenshot. Is it possible that you only restore the timer but not the switch state?

![Screenshot 2024-11-18 at 22 53 59](https://github.com/user-attachments/assets/f7f1462b-7de1-4158-9fdd-ede150173715)

**Comment by Plankske** [comment]
indeed ! Apologies for the sloppy testing. 
Will push an update to correct tomorrow. 
Thanks for your input.

**Comment by Plankske** [comment]
Patch is live now.

**Comment by spaceg00se-r** [comment]
@Plankske thanks! Testing as we speak.

**Comment by spaceg00se-r** [comment]
@Plankske Seems to work! Nice! Good job and thanks for the patch!
